### PR TITLE
Fix devblog size and list alignment

### LINKED ISSUE #11: Bulleted text is centered
Excluding the header and footer, text should NOT be centered. For some reason, bulleted text is centered, unlike the rest. The 'contribute page is a good example of this. [screenshot](https://i.imgur.com/2VOVEgR.png)

### LINKED ISSUE #12: Devblog page is huge
The media on the devblog page is huge compared to other pages but should NOT be, it should be the same size as other pages.
[screenshots](https://imgur.com/a/2A9FeCe)

### LINKED ISSUE #16: Youtube videos too wide on mobile
Youtube videos wider than the screen and everything else on the mobile site.
[screenshots](https://imgur.com/a/1Io556o)

### PR DESCRIPTION
**Pull request by TimFinucane**
Should fix #16, fix #12, and fix #11

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
This does seem to solve 11.

As well as 12; But I think the solution for 12 brings a [new issue](https://cdn.discordapp.com/attachments/668172392715255819/672560788128530452/chrome_YqlpAqCMT9.png) to the Devblog page where it doesn't align correctly...

**Comment by cosmiccoincidence** [comment]
The video in artwork.md, under the Eiko section, will need a `class="video"` as well.

**Comment by cosmiccoincidence** [comment]
I do agree with Stuben's philosophy about text not being too wide after considering it.

**Comment by TimFinucane** [comment]
I can add a max-width for text again, but we really should find some way to improve the design on desktop.
For example, i think we should still have a gallery-style element for containing images, that lays the images out best for the size of the screen.

Will fix other issues you've mentioned.

**Comment by cosmiccoincidence** [comment]
Looks good. I don't see any issues on desktop or mobile...

...just add a max-width for text to not [look so jarring on some pages](https://imgur.com/a/zNTt1eE) and this will be ready to merge imo.

**Comment by cosmiccoincidence** [comment]
(I realized I didn't need that 1st commit.. oh well.)

**Comment by TimFinucane** [comment]
Do you mind if I leave the max-width off for now? I can fix it as a separate PR but i've got to do more game work right now.

**Pull request merged**
