### PR TITLE
Updated links

### PR DESCRIPTION
**Pull request by cosmiccoincidence**
- changed github roadmap button to link to the main github page since the roadmap is seeing little use currently
- added reddit button
- removed github roadmap link in footer
- added reddit link in footer

### CODE REVIEW

**Comment by cosmiccoincidence** [comment]
Again, I'm still learning.. so I'm not sure if I have missed anything or not..

**Comment by Sunberreiy** [comment]
We don't gain anything from being officially associated with Reddit except for the responsibility of being obligated to it.

**Comment by cosmiccoincidence** [comment]
updated pr description

**Comment by cosmiccoincidence** [comment]
Re-added reddit link by popular demand in discord and updated the PR description again.

**Pull request merged**
